# Usar uma imagem base do Node.js versão 22
FROM node:22

# Definir o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copiar o arquivo de dependências
COPY package.json package-lock.json ./

# Instalar as dependências do Node.js
RUN npm install

# Copiar todo o código da aplicação para o contêiner
COPY . .

# Expor a porta que a aplicação irá rodar
EXPOSE 3000

# Comando para iniciar a aplicação Node.js
CMD ["node", "server.js"]  
